import { cn } from "../utils/cn";

/**
 * FEL DRONE — identity lockup, generated by the brand lab (docs/BRAND.md).
 *
 * The mark is one construct: the mast and arms of an F that feeds a rotor
 * disc — top arm plumb with the disc rim, tip stopping three units short of
 * the hub void, ring wall carrying the same 13-unit stroke weight as the
 * letter. No ornaments, no wing, no shield: rotation expressed through the
 * letter's own skeleton. Monochrome first; the single signal-gold element
 * is the hub.
 *
 * Geometry is locked — if the brand ever supplies a newer master, replace
 * the path data below (and public/favicon.svg + public/brand/*.svg) and
 * nothing else changes.
 */
const INK_LIGHT = "#0e1f30";
const INK_DARK = "#fbfaf8";
const ACCENT_LIGHT = "#b4823c";
const ACCENT_DARK = "#c6934a";

export default function Logo({
  className,
  dark = false,
}: {
  className?: string;
  dark?: boolean;
}) {
  const ink = dark ? INK_DARK : INK_LIGHT;
  const accent = dark ? ACCENT_DARK : ACCENT_LIGHT;
  return (
    <svg
      viewBox="0 0 679 128"
      role="img"
      aria-label="FEL DRONE"
      focusable="false"
      fill={ink}
      className={cn("h-[30px] w-auto shrink-0 lg:h-[34px]", className)}
    >
      <g transform="translate(8 8)">
          <path d="M16 8 H29 V104 H16 Z" />
          <path d="M16 8 H114.5 V21 H16 Z" />
          <path d="M16 51.5 H63.5 V64.5 H16 Z" />
          <path d="M53.5 58 a30.5 30.5 0 1 0 61 0 a30.5 30.5 0 1 0 -61 0 Z M66.5 58 a17.5 17.5 0 1 1 35 0 a17.5 17.5 0 1 1 -35 0 Z" />
          <path d="M77.5 58 a6.5 6.5 0 1 0 13 0 a6.5 6.5 0 1 0 -13 0 Z" fill={accent} />
      </g>
      <g fill="none" stroke={ink} stroke-width="9" stroke-linecap="butt" stroke-linejoin="miter">
      <path transform="translate(170 31) scale(1.03125)" d="M4.5 64 V0 H34 M4.5 29.5 H27"/>
      <path transform="translate(224.65625 31) scale(1.03125)" d="M34 0 H4.5 V64 H34 M4.5 29.5 H28"/>
      <path transform="translate(279.3125 31) scale(1.03125)" d="M4.5 0 V64 H34"/>
      <path transform="translate(356.65625 31) scale(1.03125)" d="M4.5 0 V64 M4.5 0 H21 A32 32 0 0 1 21 64 H4.5"/>
      <path transform="translate(430.90625 31) scale(1.03125)" d="M4.5 64 V0 H20 A17.75 17.75 0 0 1 20 35.5 H4.5 M20 35.5 L43 64"/>
      <path transform="translate(494.84375 31) scale(1.03125)" d="M3.5 32 a28.5 28.5 0 1 0 57 0 a28.5 28.5 0 1 0 -57 0"/>
      <path transform="translate(572.1875 31) scale(1.03125)" d="M4.5 64 V0 L37.5 64 V0"/>
      <path transform="translate(630.453125 31) scale(1.03125)" d="M34 0 H4.5 V64 H34 M4.5 29.5 H28"/>
      </g>
    </svg>
  );
}
