import { useId } from "react";
import { cn } from "../utils/cn";

/**
 * FEL DRONE — identity lockup, generated by the brand lab (docs/BRAND.md).
 *
 * The mark is one engineered construct, not an ornament: the letter F read
 * as a twin-rotor airframe seen from above. The vertical stem is the fuselage
 * spine, the two horizontal bars are rotor spars — forward spar (top bar,
 * full length) and sensor spar (middle bar, shorter) — each terminating in a
 * rotor disc whose centre is drilled through the spar. The foot is the landing
 * skid. One module rules the whole mark: the spar weight (24u) equals the
 * letter stroke, rotor 1 spans 2.16 spar widths, rotor 2 sits one spar below
 * on the optical mid-axis. No wings, no shield, no drone clipped beside an F:
 * remove the discs and it is still an F; remove the F logic and it falls
 * apart as an airframe.
 *
 * Geometry mirrors public/brand/fel-drone-*.svg exactly (brand lab gen_final).
 * If the brand ever supplies a newer master, regenerate both and nothing
 * else changes. Rotor apertures are true cut-outs (mask), so the mark lands
 * correctly on paper, navy, or photography.
 */
const INK_LIGHT = "#0e1f30";
const INK_DARK = "#fbfaf8";
const ACCENT_LIGHT = "#b4823c";
const ACCENT_DARK = "#c6934a";

// mark group: translate(9.6 1) scale(0.7) maps design space (viewBox 168×180)
// into the legacy lockup column 8..140, rows 8..120 — same optical mass as v3.
const MARK = (
  <>
    <rect x="36" y="24" width="24" height="134" />
    <rect x="36" y="24" width="98" height="24" />
    <rect x="60" y="84" width="54" height="24" />
    <rect x="24" y="146" width="72" height="24" rx="4" />
    <circle cx="134" cy="36" r="26" />
    <circle cx="114" cy="96" r="21" />
  </>
);
const HOLES = (
  <>
    <circle cx="134" cy="36" r="6" />
    <circle cx="114" cy="96" r="4.75" />
  </>
);
const HUBS = (
  <>
    <circle cx="134" cy="36" r="5.5" />
    <circle cx="114" cy="96" r="4.5" />
  </>
);

export default function Logo({
  className,
  dark = false,
}: {
  className?: string;
  dark?: boolean;
}) {
  const uid = useId().replace(/[^a-zA-Z0-9]/g, "");
  const maskId = `felmark-${uid}`;
  const ink = dark ? INK_DARK : INK_LIGHT;
  const accent = dark ? ACCENT_DARK : ACCENT_LIGHT;
  return (
    <svg
      viewBox="0 0 659 128"
      role="img"
      aria-label="FEL DRONE"
      focusable="false"
      fill={ink}
      className={cn("h-[30px] w-auto shrink-0 lg:h-[34px]", className)}
    >
      <defs>
        <mask id={maskId}>
          <rect width="100%" height="100%" fill="#fff" />
          <g fill="#000">{HOLES}</g>
        </mask>
      </defs>
      <g transform="translate(9.6 1) scale(0.7)">
        <g fill={ink} mask={`url(#${maskId})`}>{MARK}</g>
        <g fill={accent}>{HUBS}</g>
      </g>
      <g fill="none" stroke={ink} strokeWidth="9" strokeLinecap="butt" strokeLinejoin="miter">
        <path transform="translate(150 31) scale(1.03125)" d="M4.5 64 V0 H34 M4.5 29.5 H27" />
        <path transform="translate(204.65625 31) scale(1.03125)" d="M34 0 H4.5 V64 H34 M4.5 29.5 H28" />
        <path transform="translate(259.3125 31) scale(1.03125)" d="M4.5 0 V64 H34" />
        <path transform="translate(336.65625 31) scale(1.03125)" d="M4.5 0 V64 M4.5 0 H21 A32 32 0 0 1 21 64 H4.5" />
        <path transform="translate(410.90625 31) scale(1.03125)" d="M4.5 64 V0 H20 A17.75 17.75 0 0 1 20 35.5 H4.5 M20 35.5 L43 64" />
        <path transform="translate(474.84375 31) scale(1.03125)" d="M3.5 32 a28.5 28.5 0 1 0 57 0 a28.5 28.5 0 1 0 -57 0" />
        <path transform="translate(552.1875 31) scale(1.03125)" d="M4.5 64 V0 L37.5 64 V0" />
        <path transform="translate(610.453125 31) scale(1.03125)" d="M34 0 H4.5 V64 H34 M4.5 29.5 H28" />
      </g>
    </svg>
  );
}
