/** GENERATED by scripts/brand-gen.mjs — do not edit by hand (npm run brand:gen). */
export type BrandRect = { t: "rect"; x: number; y: number; w: number; h: number; rx?: number };
export type BrandCircle = { t: "circle"; cx: number; cy: number; r: number };
export type BrandShape = BrandRect | BrandCircle;
export type BrandGlyph = { d: string; x: string; y: number };

export type BrandData = {
  canvas: { w: number; h: number };
  lockup: {
    width: number;
    height: number;
    markTransform: string;
    glyphY: number;
    glyphScale: number;
    strokeWidth: number;
  };
  colors: {
    light: string;
    dark: string;
    monoBlack: string;
    monoWhite: string;
    accentLight: string;
    accentDark: string;
  };
  mark: BrandShape[];
  holes: BrandCircle[];
  hubs: BrandCircle[];
  glyphs: BrandGlyph[];
};

export const BRAND: BrandData = {
  "canvas": {
    "w": 168,
    "h": 180
  },
  "lockup": {
    "width": 659,
    "height": 128,
    "markTransform": "translate(9.600 1.000) scale(0.7)",
    "glyphY": 31,
    "glyphScale": 1.03125,
    "strokeWidth": 9
  },
  "colors": {
    "light": "#0e1f30",
    "dark": "#fbfaf8",
    "monoBlack": "#000000",
    "monoWhite": "#ffffff",
    "accentLight": "#b4823c",
    "accentDark": "#c6934a"
  },
  "mark": [
    {
      "t": "rect",
      "x": 36,
      "y": 24,
      "w": 24,
      "h": 134
    },
    {
      "t": "rect",
      "x": 36,
      "y": 24,
      "w": 98,
      "h": 24
    },
    {
      "t": "rect",
      "x": 60,
      "y": 84,
      "w": 54,
      "h": 24
    },
    {
      "t": "rect",
      "x": 24,
      "y": 146,
      "w": 72,
      "h": 24,
      "rx": 4
    },
    {
      "t": "circle",
      "cx": 134,
      "cy": 36,
      "r": 26
    },
    {
      "t": "circle",
      "cx": 114,
      "cy": 96,
      "r": 21
    }
  ],
  "holes": [
    {
      "t": "circle",
      "cx": 134,
      "cy": 36,
      "r": 6
    },
    {
      "t": "circle",
      "cx": 114,
      "cy": 96,
      "r": 4.75
    }
  ],
  "hubs": [
    {
      "t": "circle",
      "cx": 134,
      "cy": 36,
      "r": 5.5
    },
    {
      "t": "circle",
      "cx": 114,
      "cy": 96,
      "r": 4.5
    }
  ],
  "glyphs": [
    {
      "d": "M4.5 64 V0 H34 M4.5 29.5 H27",
      "x": "150",
      "y": 31
    },
    {
      "d": "M34 0 H4.5 V64 H34 M4.5 29.5 H28",
      "x": "204.65625",
      "y": 31
    },
    {
      "d": "M4.5 0 V64 H34",
      "x": "259.3125",
      "y": 31
    },
    {
      "d": "M4.5 0 V64 M4.5 0 H21 A32 32 0 0 1 21 64 H4.5",
      "x": "336.65625",
      "y": 31
    },
    {
      "d": "M4.5 64 V0 H20 A17.75 17.75 0 0 1 20 35.5 H4.5 M20 35.5 L43 64",
      "x": "410.90625",
      "y": 31
    },
    {
      "d": "M3.5 32 a28.5 28.5 0 1 0 57 0 a28.5 28.5 0 1 0 -57 0",
      "x": "474.84375",
      "y": 31
    },
    {
      "d": "M4.5 64 V0 L37.5 64 V0",
      "x": "552.1875",
      "y": 31
    },
    {
      "d": "M34 0 H4.5 V64 H34 M4.5 29.5 H28",
      "x": "610.453125",
      "y": 31
    }
  ]
};
