/** GENERATED by scripts/brand-gen.mjs — do not edit by hand (npm run brand:gen). */
export type BrandRect = { t: "rect"; x: number; y: number; w: number; h: number; rx?: number };
export type BrandCircle = { t: "circle"; cx: number; cy: number; r: number };
export type BrandShape = BrandRect | BrandCircle;
export type BrandGlyph = { d: string; x: string; y: number; w: number };

export type BrandData = {
  canvas: { w: number; h: number };
  lockup: {
    width: number;
    height: number;
    markTransform: string;
    glyphY: number;
    glyphScale: number;
  };
  colors: {
    light: string;
    dark: string;
    monoBlack: string;
    monoWhite: string;
    accentLight: string;
    accentDark: string;
  };
  mark: BrandShape[];
  holes: BrandCircle[];
  hubs: BrandCircle[];
  glyphs: BrandGlyph[];
};

export const BRAND: BrandData = {
  "canvas": {
    "w": 168,
    "h": 180
  },
  "lockup": {
    "width": 632,
    "height": 128,
    "markTransform": "translate(13.000 1.000) scale(0.7) skewX(-3)",
    "glyphY": 31,
    "glyphScale": 1.03125
  },
  "colors": {
    "light": "#0e1f30",
    "dark": "#fbfaf8",
    "monoBlack": "#000000",
    "monoWhite": "#ffffff",
    "accentLight": "#b4823c",
    "accentDark": "#c6934a"
  },
  "mark": [
    {
      "t": "rect",
      "x": 36,
      "y": 24,
      "w": 26,
      "h": 134
    },
    {
      "t": "rect",
      "x": 36,
      "y": 24,
      "w": 98,
      "h": 26
    },
    {
      "t": "rect",
      "x": 60,
      "y": 83,
      "w": 54,
      "h": 26
    },
    {
      "t": "rect",
      "x": 24,
      "y": 144,
      "w": 72,
      "h": 26,
      "rx": 4
    },
    {
      "t": "circle",
      "cx": 134,
      "cy": 36,
      "r": 26
    },
    {
      "t": "circle",
      "cx": 114,
      "cy": 96,
      "r": 21
    }
  ],
  "holes": [
    {
      "t": "circle",
      "cx": 134,
      "cy": 36,
      "r": 6
    },
    {
      "t": "circle",
      "cx": 114,
      "cy": 96,
      "r": 4.75
    }
  ],
  "hubs": [
    {
      "t": "circle",
      "cx": 134,
      "cy": 36,
      "r": 5.5
    },
    {
      "t": "circle",
      "cx": 114,
      "cy": 96,
      "r": 4.5
    }
  ],
  "glyphs": [
    {
      "d": "M6 64 V0 H32.5 M6 29.5 H25.5",
      "x": "139",
      "y": 31,
      "w": 12
    },
    {
      "d": "M32.5 0 H6 V64 H32.5 M6 29.5 H26.5",
      "x": "193.65625",
      "y": 31,
      "w": 12
    },
    {
      "d": "M6 0 V64 H32.5",
      "x": "248.3125",
      "y": 31,
      "w": 12
    },
    {
      "d": "M3.25 0 V64 M3.25 0 H19.75 A32 32 0 0 1 19.75 64 H3.25",
      "x": "302.453125",
      "y": 31,
      "w": 6.5
    },
    {
      "d": "M3.25 64 V0 H18.25 A17.75 17.75 0 0 1 18.25 35.5 H3.25 M18.25 35.5 L44.25 64",
      "x": "373.609375",
      "y": 31,
      "w": 6.5
    },
    {
      "d": "M3.25 32 a29.75 29.75 0 1 0 59.5 0 a29.75 29.75 0 1 0 -59.5 0",
      "x": "432.90625",
      "y": 31,
      "w": 6.5
    },
    {
      "d": "M3.25 64 V0 L38.75 64 V0",
      "x": "511.28125",
      "y": 31,
      "w": 6.5
    },
    {
      "d": "M35.25 0 H3.25 V64 H35.25 M3.25 29.5 H29.25",
      "x": "569.03125",
      "y": 31,
      "w": 6.5
    }
  ]
};
