/** GENERATED by scripts/brand-gen.mjs — do not edit by hand (npm run brand:gen). */
export type BrandGlyph = { d: string; x: number; y: number };

export type BrandLockup = {
  width: number;
  height: number;
  markTransform?: string;
  glyphs: BrandGlyph[];
};

export type BrandData = {
  canvas: { w: number; h: number };
  lockup: BrandLockup;
  stacked: BrandLockup;
  colors: {
    light: string;
    dark: string;
    monoBlack: string;
    monoWhite: string;
  };
  mark: string;
};

export const BRAND: BrandData = {
  "canvas": {
    "w": 136,
    "h": 160
  },
  "lockup": {
    "width": 648,
    "height": 160,
    "glyphs": [
      {
        "d": "M0 0L44 0L44 12L12 24L12 40L36 40L36 52L12 52L12 72L0 72Z",
        "x": 148,
        "y": 44
      },
      {
        "d": "M0 0L44 0L44 12L12 12L12 30L38 30L38 42L12 42L12 60L44 60L44 72L0 72Z",
        "x": 210,
        "y": 44
      },
      {
        "d": "M0 0L12 0L12 60L40 60L40 72L0 72Z",
        "x": 272,
        "y": 44
      },
      {
        "d": "M0 0L36 0L48 12L48 60L36 72L0 72ZM12 12L30 12L36 18L36 54L30 60L12 60Z",
        "x": 330,
        "y": 44
      },
      {
        "d": "M0 0L32 0L44 12L44 24L34 36L44 72L30 72L20 36L12 36L12 72L0 72ZM12 12L32 12L32 24L12 24Z",
        "x": 396,
        "y": 44
      },
      {
        "d": "M12 0L36 0L48 12L48 60L36 72L12 72L0 60L0 12ZM18 12L30 12L36 18L36 54L30 60L18 60L12 54L12 18Z",
        "x": 456,
        "y": 44
      },
      {
        "d": "M0 0L12 0L36 44L36 0L48 0L48 72L36 72L12 28L12 72L0 72Z",
        "x": 522,
        "y": 44
      },
      {
        "d": "M0 0L44 0L44 12L12 12L12 30L38 30L38 42L12 42L12 60L44 60L44 72L0 72Z",
        "x": 588,
        "y": 44
      }
    ]
  },
  "stacked": {
    "width": 516,
    "height": 248,
    "markTransform": "translate(190 -4)",
    "glyphs": [
      {
        "d": "M0 0L44 0L44 12L12 24L12 40L36 40L36 52L12 52L12 72L0 72Z",
        "x": 16,
        "y": 160
      },
      {
        "d": "M0 0L44 0L44 12L12 12L12 30L38 30L38 42L12 42L12 60L44 60L44 72L0 72Z",
        "x": 78,
        "y": 160
      },
      {
        "d": "M0 0L12 0L12 60L40 60L40 72L0 72Z",
        "x": 140,
        "y": 160
      },
      {
        "d": "M0 0L36 0L48 12L48 60L36 72L0 72ZM12 12L30 12L36 18L36 54L30 60L12 60Z",
        "x": 198,
        "y": 160
      },
      {
        "d": "M0 0L32 0L44 12L44 24L34 36L44 72L30 72L20 36L12 36L12 72L0 72ZM12 12L32 12L32 24L12 24Z",
        "x": 264,
        "y": 160
      },
      {
        "d": "M12 0L36 0L48 12L48 60L36 72L12 72L0 60L0 12ZM18 12L30 12L36 18L36 54L30 60L18 60L12 54L12 18Z",
        "x": 324,
        "y": 160
      },
      {
        "d": "M0 0L12 0L36 44L36 0L48 0L48 72L36 72L12 28L12 72L0 72Z",
        "x": 390,
        "y": 160
      },
      {
        "d": "M0 0L44 0L44 12L12 12L12 30L38 30L38 42L12 42L12 60L44 60L44 72L0 72Z",
        "x": 456,
        "y": 160
      }
    ]
  },
  "colors": {
    "light": "#0e1f30",
    "dark": "#fbfaf8",
    "monoBlack": "#000000",
    "monoWhite": "#ffffff"
  },
  "mark": "M16 20L120 20L120 32L40 52L40 80L96 80L96 96L40 96L40 140L16 140Z"
};
